dist: bionic

git:
  depth: 1

before_install:
    - sudo apt-get update -qq
    - sudo apt-get upgrade -y -qq
    - sudo apt-get install -qq ninja-build meson gfortran gfortran-mingw-w64-i686 gfortran-mingw-w64-x86-64

matrix:
    include:
        - env: CONFIGURE=""
        - env: CONFIGURE="--cross-file mingw_cross_win32.txt"
        - env: CONFIGURE="--cross-file mingw_cross_win64.txt"

script:
    - meson build $CONFIGURE
    - cd build
    - ninja
    - DESTDIR=/opt ninja install
