dist: bionic

git:
  depth: 1

before_install:
    - sudo apt-get update -qq
    - sudo apt-get upgrade -y
    - sudo apt-get install -y ninja-build meson gfortran gfortran-mingw-w64-i686 gfortran-mingw-w64-x86-64 python3-pip
    - sudo pip3 install --upgrade pip  # !! WORKAROUND way
    - sudo pip3 install --upgrade meson

matrix:
    include:
        - env: CONFIGURE=""
        - env: CONFIGURE="--cross-file crossbuild_config/mingw_cross_win32.txt"
        - env: CONFIGURE="--cross-file crossbuild_config/mingw_cross_win64.txt"

script:
    - meson build $CONFIGURE
    - cd build
    - ninja
    - DESTDIR=/opt ninja install
