# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Fortran Program Simple Compiling Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configure-parameters: ["","--host=i686-w64-mingw32"]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cat /etc/apt/sources.list && cat /etc/apt/sources.list.d/*
        sudo apt-get update
        sudo env ACCEPT_EULA=Y apt-get upgrade -y
        sudo apt-get install autotools-dev gfortran gfortran-mingw-w64-i686 inkscape-open-symbols
    - name: Fortran Compiling Test
      run: |
        ./autogen.sh
        ./configure ${{ matrix.configure-parameters }}
        make install clean
