# This workflow will install Fortran and GNU Autotools dependencies, and do compile test

name: Fortran Program with Meson Build System Simple Compiling Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        content: [""]
    steps:
    - uses: actions/checkout@v2
    - name: test again
      uses: holishing/gfortran_meson_action@2020.405.1
      with:
        matrix:
        args:  ${{ matrix.content }}
