# This workflow will install Fortran and GNU Autotools dependencies, and do compile test

name: Fortran Program with Meson Build System Simple Compiling Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        content: ["","--cross-file mingw_cross_win32.txt","--cross-file mingw_cross_win64.txt"]
    steps:
    - uses: actions/checkout@v2
    - name: core steps for building fortran programs
      uses: holishing/gfortran_meson_action@2020.405.1
      with:
        matrix:
        args:  ${{ matrix.content }}
