# This workflow will install Fortran and GNU Autotools dependencies, and do compile test

name: Fortran Program with Meson Build System Simple Compiling Test

on:
    push
    pull_request
    schedule:
    - cron: "0 2 * * 3"


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        content: ["","--cross-file crossbuild_config/mingw_cross_win32.txt","--cross-file crossbuild_config/mingw_cross_win64.txt"]
    steps:
    - uses: actions/checkout@v2
    - name: core steps for building fortran programs
      uses: holishing/gfortran_meson_action@2020.405.1
      with:
        matrix:
        args:  ${{ matrix.content }}
